CREATE DATABASE blog;
USE blog;

CREATE TABLE blogtable (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(45) NOT NULL,
  content TEXT NOT NULL,
  author VARCHAR(45) NOT NULL,
  date DATETIME DEFAULT CURRENT_TIMESTAMP, 
  status VARCHAR(45) NOT NULL,
  PRIMARY KEY (id)
);
